const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_02_00_07_27_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTM2LFxuICAgICAgICAxODYsXG4gICAgICAgIDM4LFxuICAgICAgICA3NixcbiAgICAgICAgMTMyLFxuICAgICAgICAzLFxuICAgICAgICAxODYsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTk0LFxuICAgICAgICAxNzMsXG4gICAgICAgIDE1MixcbiAgICAgICAgMjEsXG4gICAgICAgIDUxLFxuICAgICAgICAyMDgsXG4gICAgICAgIDksXG4gICAgICAgIDExMCxcbiAgICAgICAgMjAzLFxuICAgICAgICA2LFxuICAgICAgICA3MCxcbiAgICAgICAgNCxcbiAgICAgICAgMTI3LFxuICAgICAgICA1MyxcbiAgICAgICAgMjEwLFxuICAgICAgICA1MSxcbiAgICAgICAgNjcsXG4gICAgICAgIDc1LFxuICAgICAgICAxMTcsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTQ0LFxuICAgICAgICA2OSxcbiAgICAgICAgMTM0LFxuICAgICAgICA4MlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzgsXG4gICAgICAgIDIyNCxcbiAgICAgICAgNyxcbiAgICAgICAgMjE2LFxuICAgICAgICAxMzUsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMTQ1LFxuICAgICAgICA0MixcbiAgICAgICAgMjI4LFxuICAgICAgICA2OSxcbiAgICAgICAgMTg3LFxuICAgICAgICAxNyxcbiAgICAgICAgMTE3LFxuICAgICAgICA3MyxcbiAgICAgICAgMTAxLFxuICAgICAgICAyMTcsXG4gICAgICAgIDI0NixcbiAgICAgICAgMjI0LFxuICAgICAgICAxMjksXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTIwLFxuICAgICAgICA5NSxcbiAgICAgICAgMTU0LFxuICAgICAgICAzMCxcbiAgICAgICAgOTIsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyMDcsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMzcsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTc0LFxuICAgICAgICA5MyxcbiAgICAgICAgNTIsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTQyLFxuICAgICAgICAxOTMsXG4gICAgICAgIDI2LFxuICAgICAgICAxODYsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTM0LFxuICAgICAgICA5MyxcbiAgICAgICAgMTE1LFxuICAgICAgICA5NCxcbiAgICAgICAgMTY5LFxuICAgICAgICAyMDQsXG4gICAgICAgIDU5LFxuICAgICAgICA5MixcbiAgICAgICAgMTIsXG4gICAgICAgIDEyNyxcbiAgICAgICAgNjAsXG4gICAgICAgIDQ5LFxuICAgICAgICAxNyxcbiAgICAgICAgMjQxLFxuICAgICAgICAxNzUsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMjQsXG4gICAgICAgIDc1LFxuICAgICAgICAxNTgsXG4gICAgICAgIDk1LFxuICAgICAgICAxMDZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTQyLFxuICAgICAgICAxOTYsXG4gICAgICAgIDc2LFxuICAgICAgICA2OCxcbiAgICAgICAgMjA1LFxuICAgICAgICAyMTQsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTM0LFxuICAgICAgICA5OSxcbiAgICAgICAgMzgsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTA4LFxuICAgICAgICAxNDEsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTg3LFxuICAgICAgICAxMzQsXG4gICAgICAgIDYyLFxuICAgICAgICA1NixcbiAgICAgICAgMjIxLFxuICAgICAgICAyMjMsXG4gICAgICAgIDQxLFxuICAgICAgICAxNzYsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTcxLFxuICAgICAgICAxNjcsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTEsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTE0LFxuICAgICAgICAyMTgsXG4gICAgICAgIDE5LFxuICAgICAgICAyMFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA4LFxuICAgICAgICAxNjUsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTgzLFxuICAgICAgICAxNzIsXG4gICAgICAgIDEzNyxcbiAgICAgICAgNDcsXG4gICAgICAgIDksXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTc2LFxuICAgICAgICAxNzIsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMjI4LFxuICAgICAgICAyNDAsXG4gICAgICAgIDYzLFxuICAgICAgICAxMzQsXG4gICAgICAgIDIyNixcbiAgICAgICAgMjAyLFxuICAgICAgICA3NCxcbiAgICAgICAgNDgsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTE4LFxuICAgICAgICAxMjQsXG4gICAgICAgIDg3LFxuICAgICAgICA3NixcbiAgICAgICAgMTgsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMjU0LFxuICAgICAgICA2LFxuICAgICAgICAxNTIsXG4gICAgICAgIDI4LFxuICAgICAgICA4MVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyOSxcbiAgICAgICAgMjQwLFxuICAgICAgICAxNjgsXG4gICAgICAgIDE3MixcbiAgICAgICAgMjUxLFxuICAgICAgICAxMTUsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMjEyLFxuICAgICAgICAyNDMsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTk3LFxuICAgICAgICAxMzAsXG4gICAgICAgIDQsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTg0LFxuICAgICAgICA4NCxcbiAgICAgICAgNjcsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjMxLFxuICAgICAgICAyNTAsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMTY2LFxuICAgICAgICAxMzcsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTE5LFxuICAgICAgICAyMzcsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTg3LFxuICAgICAgICA5NyxcbiAgICAgICAgMTg2LFxuICAgICAgICA4OSxcbiAgICAgICAgMTAxXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIxNixcbiAgICAgICAgICAxMixcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICA2MixcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgOSxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgNDEsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDY5XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE2MixcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICA1OSxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICA2NixcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICA0NyxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICA3NyxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAxMjdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNTgsXG4gICAgICAgIDI2LFxuICAgICAgICAyMzYsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTA0LFxuICAgICAgICAxODAsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTAzLFxuICAgICAgICA5MixcbiAgICAgICAgMTcwLFxuICAgICAgICA5NyxcbiAgICAgICAgNDcsXG4gICAgICAgIDEzNSxcbiAgICAgICAgOTcsXG4gICAgICAgIDk4LFxuICAgICAgICAxNTgsXG4gICAgICAgIDkwLFxuICAgICAgICAyNDMsXG4gICAgICAgIDEzLFxuICAgICAgICAxNjAsXG4gICAgICAgIDIwNCxcbiAgICAgICAgNDQsXG4gICAgICAgIDIwNixcbiAgICAgICAgODYsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjExLFxuICAgICAgICAxNjgsXG4gICAgICAgIDU4LFxuICAgICAgICAxOTcsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTA0LFxuICAgICAgICAzMCxcbiAgICAgICAgMTIsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMjEyLFxuICAgICAgICAyMzQsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjEyLFxuICAgICAgICA5MyxcbiAgICAgICAgMTgxLFxuICAgICAgICA1NixcbiAgICAgICAgMTE3LFxuICAgICAgICAyNDIsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxMyxcbiAgICAgICAgNDgsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTkzLFxuICAgICAgICAxNzksXG4gICAgICAgIDIxMixcbiAgICAgICAgMjE0LFxuICAgICAgICA4NSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyOSxcbiAgICAgICAgMzcsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMjU0LFxuICAgICAgICAyMzUsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMjUzLFxuICAgICAgICA5NSxcbiAgICAgICAgMTc1LFxuICAgICAgICA4XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiA1NyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJiVkdyUSs5aENyNlV3VFlwQlpzYkxRQUpvSUxmeHRVbkFqZzlQNmRiMjhBPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI0MjA2NTA2OTk0M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQUExNDMyMzJERUU4MENBQURGOEYzQjVEQjZFNEVDRDlcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzIyMDQ1NjMwXG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjQyMDY1MDY5OTQzQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIxM0UzMDE2QTQ3QTNDQUI4NUExRjY4MDA1MzkzNTc1RlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjIwNDU2MzBcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiZlZkRW1ENGFRSXVPTGN1RTZSbFFQUVwiLFxuICBcInBob25lSWRcIjogXCIyYmVkMWU0Mi1mMGZjLTRiZWMtOWU4OC0yMzJmMzgyNmE2YjFcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTMwLFxuICAgICAgNjgsXG4gICAgICAxMDEsXG4gICAgICAxNjgsXG4gICAgICAyNTAsXG4gICAgICAxMjksXG4gICAgICAyMzksXG4gICAgICAxMjUsXG4gICAgICAxMTEsXG4gICAgICA4MSxcbiAgICAgIDIzMixcbiAgICAgIDE1NixcbiAgICAgIDI4LFxuICAgICAgMjA0LFxuICAgICAgMTc0LFxuICAgICAgMTc0LFxuICAgICAgMjAwLFxuICAgICAgMjMxLFxuICAgICAgMjI1LFxuICAgICAgNjNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEyMyxcbiAgICAgIDgsXG4gICAgICA2NixcbiAgICAgIDI0MCxcbiAgICAgIDIwLFxuICAgICAgMTM3LFxuICAgICAgMTM0LFxuICAgICAgMTkyLFxuICAgICAgMjAsXG4gICAgICAxNDMsXG4gICAgICAyOSxcbiAgICAgIDIzMixcbiAgICAgIDg4LFxuICAgICAgNzksXG4gICAgICAxLFxuICAgICAgMyxcbiAgICAgIDgyLFxuICAgICAgNDYsXG4gICAgICA2OCxcbiAgICAgIDQxXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDS3puZ24wUXQ2bVJ0UVlZQVNBQUtBQT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJFeSs4N1NGQWw1Qi91anVlWHZMTTN1OE1uZE9icmVJSmgxaEkyVnplVkhVPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIkw3UXA2WGl0enBveVVkZWFXT0dkYXNuWm5kWFZvSTEyTmJIK05tVDlXT3ptVjgwaTRaa3VwNExXUnVjeW1JTlVIY2JJYXJ0aGIrNXNaeG9XeVN3SkJ3PT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcImZHR1NhSW1hZU1jU2c1bU9tS21EalppQmJ0RjU3MUJxa2dDcXN6ME56ZlN3M1F3WFZhOEdJUFl0cWh5cGYyc3Q5WUdZZnlZRDAvV0NzNXpkSTVHTEF3PT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjQyMDY1MDY5OTQzOjVAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjE5NTkwMjYxODczODgwOTo1QGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIvCdmYjwnZmq8J2Zp/CdmaDwnZmu8Jakje+4juKDouKDnyDwnZmO8J2ZnfCdmZ7wnZmc8J2ZlvCdmafwnZmW8J2ZoPCdmZ5cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjI0MjA2NTA2OTk0Mzo1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgNDcsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICAzMyxcbiAgICAgICAgICA2NCxcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDksXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICA5MixcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMTE3XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjIwNDU2MjcsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFERnlcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQURGcS5qc29uIjogIntcImtleURhdGFcIjpcIm9QWEM1SjlRVUR6NGU5M1ZSbjJNNis0REduSFRxU09wRlFMOWNLS24ySlU9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjYyMTg5OTkyLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFERnIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ6R25XSHpvN0FlRkx5Wm5mdHpxQTl5ckpXTHhzY0p1QXdxR0JKSWUzeGNVPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjI2MjE4OTk5MixcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyMjAxNTkzMTYyN1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQURGcy5qc29uIjogIntcImtleURhdGFcIjpcIlE2K2VMSXNweUc5WkdjblFyeWxjNEZaSnZJY0cwSDJyVFBYY1RDVGkzQXc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjYyMTg5OTkzLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFERnQuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJKUmtKRlluL0d4R1lWdVJ0TXp0Ukt3NHkveldzRDFMZDVaZ2FiOUp5U1U0PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjI2MjE4OTk5MyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyMjA0MjYzMTU1N1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQURGdS5qc29uIjogIntcImtleURhdGFcIjpcIjY2Z0ZOcWtyUjhNM2cwVEhNdVl1WGlMaENRUzdpMThvdWFIa1lmRUQ5WEU9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjYyMTg5OTk0LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFERnYuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ4YU9laEhjZzlUVlZzYmR1OTdHbllXN2xoUW41ZEpPeVhETlZiTldSVFZJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjI2MjE4OTk5NCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyMjA0MzA1NDk2NlwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQURGdy5qc29uIjogIntcImtleURhdGFcIjpcIm9DQjk1UXRweE00UVpuSzM2SUNISVFDMmxjVnJ4VGhVdmpqSnFaVDRpbGs9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjYyMTg5OTk1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFERnguanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI2eXo1M3k5MXk4SW51U3lmLzR0SFdjbWJzTVp2N1RRbEt2bFR3NzhXaS9JPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjI2MjE4OTk5NSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyMjA0NTUyNzkzM1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQURGeS5qc29uIjogIntcImtleURhdGFcIjpcIk1hK0psZDY3Z3pQRlhUK3ZibjNqRFNIa3Rvd2JsVW1ScVZ3WmhSWFY3bTg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjYyMTg5OTk2LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjIwNDU2MzAxNTZcIn0iCn0="  


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
